security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username  # Mets "email" si tu veux la connexion par e-mail

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      user_checker: App\Security\UserChecker
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: app_home
        enable_csrf: true
      logout:
        path: app_logout
        target: app_home

  access_control:
    # PUBLIC d'abord (ordre important)
    - { path: ^/verify/email, roles: PUBLIC_ACCESS }
    - { path: ^/test-mail, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/password/reset, roles: PUBLIC_ACCESS }
    # Le reste nécessite une session
    - { path: ^/, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      App\Entity\User:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
